### ISSUE TITLE
scons -C fah-node fails

### ISSUE THREAD

**Issue by fblais** [FoldingAtHome/fah-node#4]
Running Linux Mint 21.3 (based on Ubuntu 22.04 LTS)

scons -C cbang works fine.

Then scons -C fah-node gives:

20 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

> fah-node@0.0.3 build
> node build.js

/home/francois/Téléchargements/build/fah-node/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:358
            this.signal.onabort?.(reason);
                                ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/francois/Téléchargements/build/fah-node/node_modules/esbuild-plugin-vue3/dist/index.js:89:24)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
CalledProcessError: Command '['npm', 'run', 'build']' returned non-zero exit status 1.:
  File "/home/francois/Téléchargements/build/fah-node/SConstruct", line 56:
    check_call(['npm', 'run', 'build'])
  File "/usr/lib/python3.10/subprocess.py", line 369:
    raise CalledProcessError(retcode, cmd)

Thanks in advance.

**Comment by fblais** [comment]
I was able to compile under pure debian this time.
My tests connecting to the node through Google failed though.

**Comment by jcoffland** [comment]
This looks like an ``npm`` problem to me.  Sounds like you resolved it.
